name: Security Scan

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:  # This enables manual trigger

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Semgrep
      uses: returntocorp/semgrep-action@v1
      with:
        config: auto
